export let Config = {
    startNodePressed : false,
    endNodePressed : false,
    addWallPressed : false,
    addWall : false,
    runStarted : false,
    runCompleted : true,
    startNode: -1,
    endNode: -1,
    gridRows: 1,
    gridCols: 1,
    gridCells : null,
    execute: false,
    animationTime: null,
    runButton: null,
    gridMap: null,
    clearButton: null,
    addWallButton: null,
}